mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^admin/', include(admin.site.urls)),
]

polls/urls.py
from django.conf.urls import url
from . import views

urlpatterns=[	
	# url(r'^specifics/(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
	# url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),

	url(r'^$', views.IndexView.as_view(), name='index'),
	
	#replace question_id with pk
	url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
	url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
	
	url(r'^(?P<question_id>[0-9]+)/votes/$', views.vote, name='votes'),
	]

polls/models.py
import datetime

from django.db import models
from django.utils import timezone

class Question(models.Model):
	question_text=models.CharField(max_length=200)
	pub_date=models.DateTimeField("date published")
	
	def was_published_recently(self):
		now=timezone.now()
		return now - datetime.timedelta(days=1) <=  self.pub_date <= now
	
	def __str__(self):
		return self.question_text

class Choice(models.Model):
	question=models.ForeignKey(Question)
	choice_text=models.CharField(max_length=200)
	votes=models.IntegerField(default=0)

	def __str__(self):
		return self.choice_text

polls/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.template import RequestContext, loader
from django.core.urlresolvers import reverse
from django.views import generic
from django.utils import timezone

from .models import Question, Choice

def index(request):
	latest_question_list=Question.objects.order_by('-pub_date')[:5]
	
	# different return possible :
	
	# string concatenation from a comprehensive list
	# output=', '.join([p.question_text for p in latest_question_list])
	# return HttpResponse(output)
	
	# use template
	# template=loader.get_template('polls/index.html')
	# context=RequestContext(request, {
		# 'liste_dernieres_questions':latest_question_list,
	# })	
	# return HttpResponse(template.render(context))
	
	# without loader
	context={'liste_dernieres_questions': latest_question_list}
	return render(request, 'polls/index.html', context)

""" without view
def detail(request, question_id):
  # must check if question_id exists
	
  # with try/catch
	# try:
		# question=Question.objects.get(pk=question_id)
	# except Question.DoesNotExist:
		# raise Http404("Question does not exist")
	# return render(request, 'polls/detail.html', {'question':question})
	
	question=get_object_or_404(Question, pk=question_id)
	return render(request, 'polls/detail.html', {'question':question})

def results(request, question_id):
	# version 1
	# response="You're looking at the result of question %s."
	# return HttpResponse(response %question_id)
	
	qu=get_object_or_404(Question,pk=question_id)
	return render(request, 'polls/results.html',{'question':qu})
	
def vote(request, question_id):
  # version 1
	# response="You're voting on question %s."
	# return HttpResponse(response %question_id)
	
	# v.2
	p=get_object_or_404(Question, pk=question_id)
	try:
		sel_choice=p.choice_set.get(pk=request.POST['choix'])
	except (KeyError, Choice.DoesNotExist):
		return render(request, 'poll/detail.html', {
			'question':p,
			'error_message':"You didn't select a choice.",
		})
	else:
		sel_choice.votes+=1
		sel_choice.save()
		return HttpReponseRedirect(reverse('polls:results',args=(p.id,)))
"""

class IndexView(generic.ListView):
	template_name='polls/index.html'
	context_object_name='latest_question_list'
	
	def get_queryset(self):
		# return Question.objects.order_by('-pub_date')[:5]	

		return Question.objects.filter(
			pub_date__lte=timezone.now()
		).order_by('-pub_date')[:5]
	
class DetailView(generic.DetailView):
	model=Question
	template_name='polls/detail.html'
	
	def get_queryset(self):
		return Question.objects.filter(pub_date__lte=timezone.now())
	
class ResultsView(generic.DetailView):
	model=Question
	template_name='polls/results.html'

def vote(request, question_id):
	p=get_object_or_404(Question, pk=question_id)
	try:
		sel_choice=p.choice_set.get(pk=request.POST['choice'])
	except (KeyError, Choice.DoesNotExist):
		return render(request, 'polls/detail.html', {
			'question':p,
			'error_message':"You didn't select a choice.",
		})
	else:
		sel_choice.votes+=1
		sel_choice.save()
		return HttpResponseRedirect(reverse('polls:results',args=(p.id,)))
	
	
	

polls/templates/polls/detail.html
<!-- v.1
<h1>
	{{question.question_text}}
</h1>

<ul>
#{% for choix in question.choice_set.all %}
	<li>
		{{choix.choice_text}}
	</li>
{% endfor %}
</ul>-->

<!-- v.2 -->
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}"/>

<h1>
	{{question.question_text}}
</h1>

{% if error_message %}
	<p>
		<strong>
			{{ error_message }}
		</strong>
	</p>
{% endif %}

<form action="{% url 'polls:votes' question.id %}" method="post">
	{% csrf_token %}
	{% for choice in question.choice_set.all %}
		<input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}"/>
		<label for="choice{{ forloop.counter }}">
			{{ choice.choice_text }}
		</label><br/>
	{% endfor %}
	<input type="submit" value="Vote"/>
</form>

polls/templates/polls/index.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}"/>

{% if latest_question_list %}
	Questions list
	<ul>
		{% for question in latest_question_list %}
			<li>
				
				<!--with namespace-->
				<a href="{% url 'polls:detail' question.id %}">
					{{question.question_text}}
				</a>
			</li>
		{% endfor %}
	</ul>
{% else %}
	<p>
		No polls are available.
	</p>
{% endif %}

polls/templates/polls/results.html
<h1>
	Questions Resuslts
</h1>

<ul>
	{% for choice in question.choice_set.all %}
	<li>
		{{choice.choice_text}} -- {{choice.votes}} vote{{choice.votes|pluralize}}
	</li>
	{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">
	Vote again?
<a/>